<a href="https://colab.research.google.com/github/subhojitpramanick/learning_python/blob/main/Num_Excercise_set5_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Excercise

### 1. import NumPy first

In [1]:
#code
import numpy as np

### 2. Make a 4x5 empty array

In [2]:
#code
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 3. Build a 2D array with diagonal value of 1 using positive floating numbers.

In [3]:
#code
import random
arr=np.eye(4)
for i in range(4):
  for j in range(4):
    if i==j:
      continue
    arr[i][j]=random.random()
arr

array([[1.        , 0.42529958, 0.59837515, 0.39993373],
       [0.53748505, 1.        , 0.69109387, 0.22193067],
       [0.55745993, 0.91340932, 1.        , 0.03904415],
       [0.03318604, 0.61998793, 0.6243201 , 1.        ]])

### 4. Count the total element present in first row of the above matrix.

In [4]:
#code
print(len(arr[0]))


4


### 5. Returns only even number in descending order from the existing array.

In [5]:
#input array
arr=np.array([4,5,9,8,7,20,10,11,13])

In [6]:
#code
newarr=np.array([])
for i in arr:
  if i%2==0:
    newarr=np.append(newarr,i)
newarr=newarr[::-1]
newarr


array([10., 20.,  8.,  4.])

### 6. Find the sum of first row from both array

In [7]:
#Input array
arr1=np.array([[[ 8,  9],[10, 11]],[[12, 13],[14, 15]]])
arr1

array([[[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [8]:
#code
sum=0
for i in arr1:
  sum+=np.sum(i[0])
sum


42

### 7. Make a array and change its datatype int to int16.

In [9]:
#code
arr=np.array([[[16, 17],[18, 19]],[[20, 21],[22, 23]]],dtype='int16')
print(arr.dtype)


int16


### 8. Calculate the sum of the diagonal element of the matrix

In [10]:
#input Array
m = np.arange(32,48).reshape(4,4)
m

array([[32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [11]:
#code
dsum=0
for i in range(4):
  dsum+=m[i][i]
dsum


158

### 9. Create an (8,2) matrix from the above matrix (value will be same)

In [12]:
#code
m.reshape(8,2)


array([[32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47]])

### 10. Create a function which calculate sigmoid of an numpy array.


In [13]:
# Input array
arr2=np.array([4,5,9,8,7])
arr2

array([4, 5, 9, 8, 7])

In [14]:
#code
def sigmoid(arr):
  return 1/(1+np.exp(-arr))
sigmoid(arr2)


array([0.98201379, 0.99330715, 0.99987661, 0.99966465, 0.99908895])

### 11. Multiply 5 with all the element of first row and last row from the matrix.

In [15]:
# Input array
arr3=np.array([[56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71]])
arr3

array([[56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71]])

In [16]:
#code
new=arr3[0:4:2,0:4]
new*5


array([[280, 285, 290, 295],
       [320, 325, 330, 335]])

### 12. What is the index value of maximum number present in middle row

In [17]:
#code
arr=np.array([[44 ,88 ,20],[85, 74 ,56],[41 ,23 ,56]])
print(f"Maximum number in middle row is in index {np.argmax(arr[1])}")


Maximum number in middle row is in index 0


### 13. Calculate the sin value of all the element present in the vector

In [18]:
#Input array
arr=np.array([12,56,41,23,44,11])

In [19]:
#code
new=np.sin(arr)
new

array([-0.53657292, -0.521551  , -0.15862267, -0.8462204 ,  0.01770193,
       -0.99999021])

### 14. Make two 2D arrays and do subtraction between them.

In [20]:
#code
arr1=np.array([[2,3,4],[6,7,8]])
arr2=np.array([[1,2,3],[4,5,6]])
arr1-arr2


array([[1, 1, 1],
       [2, 2, 2]])

### 15. Access the last three element from the 1D array and reverse the result

In [21]:
# Input array
arr=np.array([41,52,3,88,14,56,10])

In [22]:
#code
new=arr[-3:][::-1]
new


array([10, 56, 14])

### 16. Access second and third row from below matrix

In [23]:
d = np.arange(5,25).reshape(4,5)
d

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
#code
d[1:3]


array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 17. Access Below part from above matrix

In [25]:
#code
d[1:3:,2:4]

array([[12, 13],
       [17, 18]])

### 18. Access Below part

In [26]:
#code
d[2:,:2]

array([[15, 16],
       [20, 21]])

### 19. Access below part

In [27]:
#code
d[2:3,1:4]

array([[16, 17, 18]])

### 20.Access these part from below matrix

In [28]:
h=np.arange(0,24).reshape(2,4,3)
h

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [29]:
#code
h[0:,1:4:2,1:3]


array([[[ 4,  5],
        [10, 11]],

       [[16, 17],
        [22, 23]]])